name: Deploy Sanity Studio

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'studio/**'
      - '.github/workflows/sanity-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd studio
          npm install

      - name: Deploy to Sanity
        run: |
          cd studio
          npx sanity deploy --yes
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
